name: Frontend deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
       - run: echo "Pipeline testing..."

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.22'
      - name: Snyk monitor
        run: snyk test
        env:
          SNYK_TOKEN: 6b2ca679-e7e1-4870-af6d-70f7a3c0c26f
