name: Frontend deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4

    - name: Create new file
      run: |
        mkdir -p w/x/y
        echo "This is new file from pipeline.${{ github.head_ref }}.${{ github.sha }}" > w/x/y/new_temp.txt

    - name: Upload to gdrive
      uses: adityak74/google-drive-upload-git-action@main
      with:
        credentials: ${{ secrets.CREDENTIALS }}
        filename: "w/x/y/new_temp.txt"
        folderId: ${{ secrets.FOLDER_ID }}
        name: "target_name.txt" # optional string
        overwrite: "true" # optional boolean
        mirrorDirectoryStructure: "true"
